"""This file provides a dictionary of all known jukebox IDs"""

jukebox_data_for_ID = {
    "000000CAD5EC": {
        "Location name": "American Legion (Scottsburg)",
        "Location ID": "L140059",
        "Jukebox model": "Ovation II",
        "Computer": "MHP",
        "Software": "OS2_US_BASE",
        "Version": "2.28.1-12",
    },
    "000000B2EC1F": {
        "Location name": "American Legion Post 28",
        "Location ID": "L191561",
        "Jukebox model": "Digital Conversion Kit",
        "Computer": "JCB 1.2Ghz",
        "Software": "GEN3",
        "Version": "4.7.33-2",
    },
    "00000042E849": {
        "Location name": "American Legion Post 42",
        "Location ID": "L226972",
        "Jukebox model": "Allegro",
        "Computer": "JCB+",
        "Software": "GEN3",
        "Version": "4.7.35-2",
    },
    "0000000A94D3": {
        "Location name": "Amvets Post 9",
        "Location ID": "L316177",
        "Jukebox model": "Angelina",
        "Computer": "MHP",
        "Software": "OS2_US_BASE",
        "Version": "2.28.1-12",
    },
    "0000000A7F11": {
        "Location name": "BACKROOM RAILYARD BILLIARDS",
        "Location ID": "L300266",
        "Jukebox model": "Angelina",
        "Computer": "MHP",
        "Software": "OS2_US_BASE",
        "Version": "2.28.2-9",
    },
    "0000000A8A0B": {
        "Location name": "Cluckers Jeffersonville",
        "Location ID": "L29715",
        "Jukebox model": "Angelina",
        "Computer": "MHP",
        "Software": "OS2_US_BASE",
        "Version": "2.28.2-9",
    },
    "0000000A8C27": {
        "Location name": "Cluckers Versailles",
        "Location ID": "L320511",
        "Jukebox model": "Angelina",
        "Computer": "MHP",
        "Software": "OS2_US_BASE",
        "Version": "2.28.1-12",
    },
    "0000004171AD": {
        "Location name": "Crothersville VFW",
        "Location ID": "L186658",
        "Jukebox model": "CD Conversion Kit",
        "Computer": "JCB+",
        "Software": "GEN3",
        "Version": "4.7.35-2",
    },
    "0000000A587A": {
        "Location name": "El Maguey",
        "Location ID": "L282034",
        "Jukebox model": "Angelina",
        "Computer": "MHP",
        "Software": "OS2_US_BASE",
        "Version": "2.28.1-12",
    },
    "0000000AA359": {
        "Location name": "El Maguey Salem",
        "Location ID": "L324820",
        "Jukebox model": "Angelina",
        "Computer": "MHP",
        "Software": "OS2_US_BASE",
        "Version": "2.28.1-12",
    },
    "000000BF2CB7": {
        "Location name": "FOEagles",
        "Location ID": "L94516",
        "Jukebox model": "Virtuo",
        "Computer": "i3",
        "Software": "OS2_US_BASE",
        "Version": "2.28.2-9",
    },
    "0000000A5B40": {
        "Location name": "GOLDEN NUGGET",
        "Location ID": "L238364",
        "Jukebox model": "Fusion",
        "Computer": "MHP",
        "Software": "OS2_US_BASE",
        "Version": "2.28.2-9",
    },
    "The entry below is because touchtunes reports the device ID wrong": "No idea why",
    "0000000A5B4": {
        "Location name": "GOLDEN NUGGET",
        "Location ID": "L238364",
        "Jukebox model": "Fusion",
        "Computer": "MHP",
        "Software": "OS2_US_BASE",
        "Version": "2.28.2-9",
    },
    "0000000A7276": {
        "Location name": "Harry's backroom",
        "Location ID": "L290950",
        "Jukebox model": "Angelina",
        "Computer": "MHP",
        "Software": "OS2_US_BASE",
        "Version": "2.28.2-9",
    },
    "0000003D2C72": {
        "Location name": "HOBART BEACH VFW",
        "Location ID": "L177134",
        "Jukebox model": "Ovation",
        "Computer": "JCB+",
        "Software": "GEN3",
        "Version": "4.7.35-2",
    },
    "0000000A94E3": {
        "Location name": "Hoopsters Sports Bar jeff",
        "Location ID": "L157125",
        "Jukebox model": "Angelina",
        "Computer": "MHP",
        "Software": "OS2_US_BASE",
        "Version": "2.28.1-12",
    },
    "000000E36408": {
        "Location name": "Krazy Dave's",
        "Location ID": "L238362",
        "Jukebox model": "Virtuo",
        "Computer": "i3",
        "Software": "OS2_US_BASE",
        "Version": "2.28.1-11",
    },
    "0000000A304F": {
        "Location name": "Mac's Hideaway",
        "Location ID": "L19008",
        "Jukebox model": "Virtuo 2",
        "Computer": "i3",
        "Software": "OS2_US_BASE",
        "Version": "2.28.1-12",
    },
    "0000000A6787": {
        "Location name": "Mick's Lounge",
        "Location ID": "L115484",
        "Jukebox model": "Angelina",
        "Computer": "MHP",
        "Software": "OS2_US_BASE",
        "Version": "2.28.1-12",
    },
    "0000000A79CC": {
        "Location name": "Our Lady of Perpetual Hops",
        "Location ID": "L299993",
        "Jukebox model": "Angelina",
        "Computer": "MHP",
        "Software": "OS2_US_BASE",
        "Version": "2.28.1-12",
    },
    "0000000A551C": {
        "Location name": "Pearl Street Taphouse",
        "Location ID": "L252131",
        "Jukebox model": "Fusion",
        "Computer": "MHP",
        "Software": "OS2_US_BASE",
        "Version": "2.28.1-12",
    },
    "00000042C2BE": {
        "Location name": "Pizza Place",
        "Location ID": "L146878",
        "Jukebox model": "CD Conversion Kit",
        "Computer": "JCB 1.2Ghz",
        "Software": "GEN3",
        "Version": "4.7.33-2",
    },
    "0000000A7865": {
        "Location name": "POOLROOM RAILYARD BILLARDS",
        "Location ID": "L292988",
        "Jukebox model": "Angelina",
        "Computer": "MHP",
        "Software": "OS2_US_BASE",
        "Version": "2.28.1-12",
    },
    "000000BF0ABA": {
        "Location name": "Post 204 Am.Legion Sellersburg",
        "Location ID": "L267083",
        "Jukebox model": "Virtuo",
        "Computer": "i3",
        "Software": "OS2_US_BASE",
        "Version": "2.28.1-12",
    },
    "0000005F3F8C": {
        "Location name": "Pride Bar",
        "Location ID": "L286705",
        "Jukebox model": "Playdium",
        "Computer": "i3",
        "Software": "OS2_US_BASE",
        "Version": "2.28.2-9",
    },
    "00000043455C": {
        "Location name": "Resch's Tavern",
        "Location ID": "L37224",
        "Jukebox model": "Ovation",
        "Computer": "MHP",
        "Software": "OS2_US_BASE",
        "Version": "2.28.1-12",
    },
    "0000003C2954": {
        "Location name": "Rubbin¿ Butts BBQ",
        "Location ID": "L316580",
        "Jukebox model": "Ovation",
        "Computer": "MHP",
        "Software": "OS2_US_BASE",
        "Version": "2.28.1-12",
    },
    "000000BF26D0": {
        "Location name": "THE DERBY HOTEL",
        "Location ID": "L271746",
        "Jukebox model": "Virtuo",
        "Computer": "i3",
        "Software": "OS2_US_BASE",
        "Version": "2.28.1-12",
    },
    "0000000A913D": {
        "Location name": "The Dock Restaurant and Bar",
        "Location ID": "L311260",
        "Jukebox model": "Angelina",
        "Computer": "MHP",
        "Software": "OS2_US_BASE",
        "Version": "2.28.1-12",
    },
    "0000000A77B7": {
        "Location name": "Thirsty's",
        "Location ID": "L184415",
        "Jukebox model": "Angelina",
        "Computer": "MHP",
        "Software": "OS2_US_BASE",
        "Version": "2.28.0-15",
    },
    "0000000A60C8": {
        "Location name": "VFW - Austin",
        "Location ID": "L153837",
        "Jukebox model": "Angelina",
        "Computer": "MHP",
        "Software": "OS2_US_BASE",
        "Version": "2.28.2-9",
    },
    "0000000A7EE5": {
        "Location name": "VFW 1427 Charlestown",
        "Location ID": "L304478",
        "Jukebox model": "Angelina",
        "Computer": "MHP",
        "Software": "OS2_US_BASE",
        "Version": "2.28.2-9",
    },
    "000000481201": {
        "Location name": "VFW 1832",
        "Location ID": "L42773",
        "Jukebox model": "Ovation JCB Upgrade",
        "Computer": "MHP",
        "Software": "OS2_US_BASE",
        "Version": "2.28.2-9",
    },
    "000000433419": {
        "Location name": "VFW 3281",
        "Location ID": "L225376",
        "Jukebox model": "Allegro",
        "Computer": "JCB+",
        "Software": "GEN3",
        "Version": "4.7.35-2",
    },
    "0000000A79CD": {
        "Location name": "Vic's Cafe",
        "Location ID": "L175027",
        "Jukebox model": "Angelina",
        "Computer": "MHP",
        "Software": "OS2_US_BASE",
        "Version": "2.28.1-12",
    },
    "000000422B5B": {
        "Location name": "WAREHOUSE",
        "Location ID": "L255670",
        "Jukebox model": "Allegro",
        "Computer": "JCB+",
        "Software": "GEN3",
        "Version": "4.7.18-2",
    },
    "000000487832": {
        "Location name": "WAREHOUSE",
        "Location ID": "L255670",
        "Jukebox model": "CD Conversion Kit",
        "Computer": "JCB+",
        "Software": "GEN3",
        "Version": "4.7.33-2",
    },
    "000000FCC271": {
        "Location name": "WAREHOUSE",
        "Location ID": "L255670",
        "Jukebox model": "Virtuo",
        "Computer": "Core 2 Duo",
        "Software": "OS2_US_BASE",
        "Version": "2.27.3-9",
    },
    "0000000A91CF": {
        "Location name": "WAREHOUSE",
        "Location ID": "L255670",
        "Jukebox model": "Angelina",
        "Computer": "MHP",
        "Software": "OS2_US_BASE",
        "Version": "2.28.1-11",
    },
    "0000001F9AEC": {
        "Location name": "WAREHOUSE",
        "Location ID": "L255670",
        "Jukebox model": "Virtuo",
        "Computer": "Core 2 Duo",
        "Software": "OS2_US_BASE",
        "Version": "2.27.2-14",
    },
    "0000000A6F21": {
        "Location name": "WAREHOUSE",
        "Location ID": "L255670",
        "Jukebox model": "Angelina",
        "Computer": "MHP",
        "Software": "OS2_US_BASE",
        "Version": "2.28.1-11",
    },
    "000000352A12": {
        "Location name": "WAREHOUSE",
        "Location ID": "L255670",
        "Jukebox model": "Maestro",
        "Computer": "JCB 1.2Ghz",
        "Software": "GEN3",
        "Version": "4.7.33-2",
    },
    "0000002AA1AE": {
        "Location name": "WAREHOUSE",
        "Location ID": "L255670",
        "Jukebox model": "Gen1 / Gen2 Gen3 Upgrade",
        "Computer": "JCB 1.2Ghz",
        "Software": "GEN3",
        "Version": "4.7.31-2",
    },
}
